url: https://sirajinstitute.github.io
baseurl: /

# Site settings
title: Siraj Institute
email: info@Siraj.institute
description: "Providing quality Islamic education, mentorship and community engagement for Canadian Muslims."


# Team names, titles and social links
people:
- name: Majed Jarrar
  pic: 1
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Hesham Saleh
  pic: 2
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ahmed Gabr
  pic: 3
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
 - name: Omer Jamshaid
  pic: 4
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/SirajInstituteCA/

# Postal address (add as many lines as necessary)
address:
  - line: 25 Templeton Street, Office 315
  - line: Ottawa, ON K1N 6N5

# Build settings
markdown: kramdown
permalink: pretty
